add_newline = false

[line_break]
disabled = true

[aws]
symbol = " "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "
disabled = false

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = false

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
disabled = false

[sudo]
disabled = false

