{
  inputs,
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    # Core Ultra X7 358H (Panther Lake) mainboard.
    inputs.hardware.nixosModules.framework-intel-core-ultra-series3

    inputs.agenix.nixosModules.default

    ./hardware-configuration.nix

    ./nix-ld.nix
    ./syncthing.nix

    ../common/global
    ../common/tailscale.nix
    ../common/pipewire.nix
    ../common/virtualisation.nix
    ../common/steam.nix
    ../common/fleet-ssh.nix
    ../common/workspace-secrets.nix

    ../common/cosmic.nix
  ];

  # No sshd, so the agenix machine identity is generated by hand
  # (docs/runbooks/backup-recovery.md, "Bootstrap sencha's agenix identity").
  # Add secrets + ./backup.nix once fleet.nix has the host key.
  age.identityPaths = ["/etc/ssh/ssh_host_ed25519_key"];

  fleet.workspaceSecrets.account = "lanice";

  # Boot into Cosmic by default; pick the "gnome" entry in systemd-boot to switch.
  desktops.cosmic.enable = lib.mkDefault true;

  # Mirror the system-side desktop flag into home-manager so per-spec HM follows.
  home-manager.users.lanice.desktops.cosmic.enable = config.desktops.cosmic.enable;

  networking = {
    hostName = "longjing";
    networkmanager.enable = true;
  };

  # See https://github.com/NixOS/nixpkgs/issues/180175#issuecomment-1473408913
  systemd.services.NetworkManager-wait-online.enable = false;

  # Bootloader comes from ../common/global/systemd-boot.nix.
  boot.loader.systemd-boot.configurationLimit = 30;
  boot.loader.efi.canTouchEfiVariables = true;
  # Panther Lake wants a current kernel; the hardware module only forces
  # linuxPackages_latest when the default is older than 6.17.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  programs = {
    dconf.enable = true;
    solaar = {
      enable = true;
      userService.enable = true;
    };
  };

  xdg.portal.enable = true;

  hardware = {
    graphics.enable = true;
    bluetooth.enable = true;
    bluetooth.powerOnBoot = true;
  };

  environment = {
    enableAllTerminfo = false;
    systemPackages = with pkgs; [
      libva-utils
      inputs.agenix.packages.x86_64-linux.default
    ];
    sessionVariables.NIXOS_OZONE_WL = "1";
    variables.MOZ_DISABLE_RDD_SANDBOX = "1";
  };

  services.hardware.bolt.enable = true;

  services.tailscale.useRoutingFeatures = "client";

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  system.stateVersion = "26.05";
}
