{
  imports = [
    ../../common/mail.nix
    ../../common/publishing.nix

    ./adguard.nix
    ./backup-landing.nix
    ./backup.nix
    ./audiobookrequest.nix
    ./aurral.nix
    ./bookorbit
    ./explo.nix
    ./forgejo-runner.nix
    ./healthcheck.nix
    ./homepage.nix
    ./librechat.nix
    ./lidarr.nix
    ./media-estate.nix
    ./media.nix
    ./paperless.nix
    ./peertube.nix
    ./sabnzbd.nix
    ./scrutiny.nix
    ./shelfmark.nix
    ./sillytavern.nix
    ./soulseek.nix
    ./speedtest-tracker.nix
    ./stirlingpdf.nix
    ./syncthing.nix
    ./tracearr.nix
    ./uptime-kuma.nix
    ./zfs-zed.nix
  ];
}
