let
  fleet = import ../hosts/fleet.nix;
  inherit (fleet.users) lanice-sencha lanice-longjing lanice-unstable;
  admins = [lanice-sencha lanice-longjing];

  unstable = fleet.hosts.unstable.hostKey;
  sencha = fleet.hosts.sencha.hostKey;
  boba = fleet.hosts.boba.hostKey;
  taro = fleet.hosts.taro.hostKey;
  longjing = fleet.hosts.longjing.hostKey;
in {
  "workspaceAgeSencha.age".publicKeys = [sencha] ++ admins;
  "workspaceAgeTaro.age".publicKeys = [taro] ++ admins;
  "workspaceAgeLongjing.age".publicKeys = [longjing] ++ admins;
  "porkbun.age".publicKeys = [unstable boba taro lanice-unstable] ++ admins;
  "porkbunApiKey.age".publicKeys = [boba] ++ admins;
  "porkbunSecretApiKey.age".publicKeys = [boba] ++ admins;
  "homepage.age".publicKeys = [boba] ++ admins;
  "librechat.env.age".publicKeys = [boba] ++ admins;
  "mailBobaPassword.age".publicKeys = [boba] ++ admins;
  "sabnzbd.age".publicKeys = [boba] ++ admins;
  "shelfmark.age".publicKeys = [boba] ++ admins;
  "bookorbit.age".publicKeys = [boba] ++ admins;
  "slskd.age".publicKeys = [boba] ++ admins;
  "healthcheck-uuid.age".publicKeys = [boba] ++ admins;
  "peertube-secrets.age".publicKeys = [boba] ++ admins;
  "peertube-db-password.age".publicKeys = [boba] ++ admins;
  "explo.age".publicKeys = [boba] ++ admins;
  "speedtest-tracker-app-key.age".publicKeys = [boba] ++ admins;
  "forgejo-runner-token.age".publicKeys = [boba] ++ admins;
  "resticB2Credentials.age".publicKeys = [boba] ++ admins;
  "resticOffsiteHealthcheckUuid.age".publicKeys = [boba] ++ admins;
  "resticSenchaHealthcheckUuid.age".publicKeys = [sencha] ++ admins;
  "resticMonthlyHealthcheckUuid.age".publicKeys = [boba] ++ admins;
  "resticHtpasswd.age".publicKeys = [boba] ++ admins;
  "resticSenchaTransport.age".publicKeys = [sencha] ++ admins;
  "resticForgejoTransport.age".publicKeys = [taro] ++ admins;
  "resticMailArchiveTransport.age".publicKeys = [taro] ++ admins;
  "resticBobaTransport.age".publicKeys = [boba] ++ admins;
  "resticSenchaPassword.age".publicKeys = [sencha boba] ++ admins;
  "resticForgejoPassword.age".publicKeys = [taro boba] ++ admins;
  "resticBobaPassword.age".publicKeys = [boba] ++ admins;
  "resticOffsiteSenchaPassword.age".publicKeys = [boba] ++ admins;
  "resticOffsiteForgejoPassword.age".publicKeys = [boba] ++ admins;
  "resticOffsiteMailArchivePassword.age".publicKeys = [boba] ++ admins;
  "resticOffsiteBobaPassword.age".publicKeys = [boba] ++ admins;
  "forgejo-dump-key.age".publicKeys = [taro] ++ admins;
  "mailTaroPassword.age".publicKeys = [taro] ++ admins;
  "mailArchiveUsers.age".publicKeys = [taro] ++ admins;
  "mailArchiveSyncPassword.age".publicKeys = [taro] ++ admins;
  "mailSourcePasswords.age".publicKeys = [taro] ++ admins;
  "mailArchiveResticPassword.age".publicKeys = [taro boba] ++ admins;
  "mailArchiveHealthcheckUuid.age".publicKeys = [taro] ++ admins;
}
